# Generated by Django 4.1.7 on 2023-03-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_description', models.TextField()),
                ('cat_slug', models.SlugField()),
                ('cat_is_active', models.BooleanField(default=False)),
                ('cat_sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_model', to='home.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_price', models.CharField(max_length=100)),
                ('pro_desc', models.TextField()),
                ('pro_active', models.BooleanField(default=False)),
                ('pro_numb', models.SmallIntegerField()),
                ('pro_slug', models.SlugField(unique=True)),
                ('pro_image', models.ImageField(upload_to='pro_image')),
                ('pro_sizes', models.CharField(blank=True, help_text='separate sizes with comma (,)', max_length=255, null=True)),
                ('pro_cat', models.ManyToManyField(related_name='pro_model', to='home.categorymodel')),
            ],
        ),
    ]
