# Generated by Django 4.1.4 on 2022-12-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_description', models.TextField()),
                ('cat_slug', models.SlugField()),
                ('cat_is_active', models.BooleanField(default=False)),
                ('cat_sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_model', to='home.categorymodel')),
            ],
        ),
    ]
