# Generated by Django 4.1.4 on 2022-12-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_categorymodel_cat_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_price', models.IntegerField()),
                ('pro_desc', models.TextField()),
                ('pro_active', models.BooleanField(default=False)),
                ('pro_numb', models.SmallIntegerField()),
                ('pro_slug', models.SlugField()),
                ('pro_image', models.ImageField(upload_to='')),
                ('pro_cat', models.ManyToManyField(related_name='pro_model', to='home.categorymodel')),
            ],
        ),
    ]
