# Generated by Django 4.1.4 on 2022-12-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pro_sizes',
            field=models.CharField(blank=True, help_text='separate sizes with comma (,)', max_length=255, null=True),
        ),
    ]
