# Generated by Django 4.1.4 on 2022-12-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_productmodel_pro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pro_image',
            field=models.ImageField(upload_to='pro_image'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pro_price',
            field=models.CharField(max_length=100),
        ),
    ]
