# Generated by Django 4.1.7 on 2023-03-01 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_size', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_proo', to='home.productmodel')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_userr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_size', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_pro', to='home.productmodel')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
