# Generated by Django 4.1.7 on 2023-03-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymodel',
            old_name='order_size',
            new_name='order_sizes',
        ),
        migrations.RenameField(
            model_name='paymodel',
            old_name='pro_order',
            new_name='pro_orders',
        ),
        migrations.RenameField(
            model_name='paymodel',
            old_name='user_order',
            new_name='user_orders',
        ),
    ]
