# Generated by Django 4.1.7 on 2023-02-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_paid', to='order.ordermodel')),
            ],
        ),
    ]
